---
title: Similarity over time
author: Molly Lewis 
date: "`r Sys.Date()`"
output: 
  html_document:
    toc: true
    number_sections: false
    theme: cerulean
    toc_float: false
    code_folding: hide
---
  
  
```{r setup, include = F}
# load packages
library(tidyverse) 
library(knitr)
library(here)
library(anytime)
library(tidytext)

opts_chunk$set(echo = T, message = F, warning = F, 
               error = F, tidy = F,  cache = T, fig.height = 4)
theme_set(theme_void())
source(here("exploratory_analyses/01_reddit_pilot/scripts/make_corr_plot.R"))
``` 

```{r}
PAIRWISE_TOPIC_JSD <- here("exploratory_analyses/01_reddit_pilot/data/post_JSD_pittsburgh.csv")
SUBREDDIT_DATA_PATH <- here("exploratory_analyses/01_reddit_pilot/data/pittsburgh2years_tidy.csv")

topic_jsd <- read_csv(PAIRWISE_TOPIC_JSD)
tidy_comments <- read_csv(SUBREDDIT_DATA_PATH, 
                          guess_max = 1000000)  

tidy_comments_tidy <- tidy_comments %>%
  select(subreddit, post_id, comment_id, author, created_utc) %>%
  mutate(created_bin = lubridate::round_date(created_utc, "week")) %>%
  unite(document1, c(subreddit, post_id, comment_id), sep = "-") %>%
  mutate(document2 = document1) %>%
  select(contains("document"), everything()) %>%
  select(-created_utc) 

topic_jsd_with_meta <- topic_jsd %>%
  left_join(tidy_comments_tidy %>% 
              select(document1, created_bin)) %>%
  rename(created_bin1 = created_bin) %>%
  left_join(tidy_comments_tidy %>% 
              select(document2, created_bin)) %>%
  rename(created_bin2 = created_bin)
```

## Posts over time
```{r}
same_bin <- topic_jsd_with_meta %>%
  filter(created_bin1 == created_bin2)

jsd_by_bin <- same_bin %>%
  group_by(created_bin1, created_bin2) %>%
  summarize(mean_jsd = mean(jsd))

ggplot(jsd_by_bin, aes(x = created_bin1, y = mean_jsd)) +
  geom_point() +
  geom_smooth() +
  xlab("Post date (week)") +
  ylab("Mean JSD") +
  geom_smooth(method = "lm",color = "red" ) +
  ggtitle("Post similarity over community time (PGH)") +
  theme_classic(base_size = 14)
```

## Self similarity over posts
```{r}

tidy_comments_tidy_author <- tidy_comments %>%
  select(subreddit, post_id, comment_id, author, created_utc) %>%
  unite(document1, 
        c(subreddit, post_id, comment_id),
        sep = "-") %>%
  mutate(document2 = document1) %>%
  filter(document1 %in% unique(topic_jsd$document1),
         document2 %in% unique(topic_jsd$document2)) %>%
  select(contains("document"), everything()) %>%
  arrange(author, created_utc) %>%
  group_by(author) %>%
  mutate(nth_post = 1:n()) %>%
  select(-created_utc) %>%
  ungroup()

topic_jsd_with_meta_author <- topic_jsd %>%
  left_join(tidy_comments_tidy_author %>% 
              select(document1, author, nth_post)) %>%
  rename(nth_post1 = nth_post,
         author1 = author) %>%
  left_join(tidy_comments_tidy_author %>% 
              select(document2, author, nth_post)) %>%
  rename(nth_post2 = nth_post,
         author2 = author)

same_author <- topic_jsd_with_meta_author %>%
  filter(author1 == author2) %>%
  mutate(post_diff = nth_post2 - nth_post1)  %>%
  filter(post_diff == 1) %>%
  arrange(author1, nth_post1)

mean_jsd_by_postn <- same_author %>%
  filter(nth_post1 <= 50) %>%
  group_by(nth_post1) %>%
  tidyboot::tidyboot_mean(col = jsd) 

ggplot(mean_jsd_by_postn, 
       aes(x = nth_post1, y = mean)) +
  geom_point(aes(size = n)) +
  geom_linerange(aes(ymin = ci_lower, ymax = ci_upper))+
  xlab("Nth post") +
  ylab("Mean JSD") +
  #geom_smooth(method = "lm",color = "red" ) +
  ggtitle("Self similarity over individual time (PGH)") +
  theme_classic(base_size = 14)
```

# by centrality
```{r}
social_data <- tidy_comments %>%
  select(subreddit, parent_id, comment_id, author) %>%
  left_join(tidy_comments %>% distinct(comment_id, author) %>%
              rename(parent_author = author), 
            by = c("parent_id" = "comment_id")) %>%
  filter(!is.na(parent_id), 
         !is.na(parent_author), 
         parent_author != "[deleted]")

social_graph_data  <- social_data %>%
  count(author, parent_author) %>%
  mutate_if(is.character, as.factor) 

social_graph <- social_graph_data %>%
  filter(author %in% unique(social_graph_data$parent_author),
         parent_author %in% unique(social_graph_data$author)) %>%
  rename(from = parent_author,
         to = author) %>%
  as_tbl_graph(directed = F) %>%
  activate(nodes) %>%  # Remove isolated nodes
  mutate(centrality = centrality_degree(mode = 'in')) %>%
  filter(!node_is_isolated(),
         !node_is_simplical()) %>%
  as_tibble()

by_author_JSD <- topic_jsd_with_meta_author %>%
  filter(author1 == author2) %>%
  group_by(author1) %>%
  summarize(mean_jsd = mean(jsd),
            n = n())
  
full_jsd_social <- social_graph %>%
  inner_join(by_author_JSD, by = c("name" = "author1"))

full_jsd_social %>%
  ggplot(aes(x = log(centrality), y = mean_jsd)) +
  geom_point(aes(size = log(n)), alpha = .2) +
  ylab("Mean JSD") +
  geom_smooth(method = "lm",color = "red" ) +
  ggtitle("Self similarity as a function of social position (PGH)") +
  theme_classic(base_size = 14)

lm(mean_jsd ~ log(centrality) + log(n), full_jsd_social) %>%
  summary() %>%
  tidy() %>%
  kable()
```

```{r}

community similarity over time: http://rpubs.com/mll/538196
self similarity over time: http://rpubs.com/mll/538194
self similarity as a function of place in social network: http://rpubs.com/mll/538191

```
